<a href="https://colab.research.google.com/github/raisaksh1/Machine-Learning/blob/main/NBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/titanic (1).csv')

In [ ]:
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [ ]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis = 'columns', inplace = True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [ ]:
inputs = df.drop('Survived', axis = 'columns')
target = df.Survived

In [ ]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [ ]:
inputs = pd.concat([inputs, dummies], axis = 'columns')
inputs.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [ ]:
inputs.drop(['Sex', 'male'], axis = 'columns', inplace = True)
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [ ]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [ ]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [ ]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.3)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
model.fit(X_train, y_train)

GaussianNB()

In [ ]:
model.score(X_test, y_test)

0.7761194029850746

In [ ]:
X_test[0:10]

Pclass        Age      Fare  female
774       2  54.000000   23.0000       1
572       1  36.000000   26.3875       0
336       1  29.000000   66.6000       0
531       3  29.699118    7.2292       0
283       3  19.000000    8.0500       0
811       3  39.000000   24.1500       0
88        1  23.000000  263.0000       1
379       3  19.000000    7.7750       0
34        1  28.000000   82.1708       0
671       1  31.000000   52.0000       0

In [ ]:
y_test[0:10]

774    1
572    1
336    0
531    0
283    1
811    0
88     1
379    0
34     0
671    0
Name: Survived, dtype: int64

In [ ]:
model.predict(X_test[0:10])

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [ ]:
model.predict_proba(X_test[0:10])

array([[2.54911111e-01, 7.45088889e-01],
       [8.05059377e-01, 1.94940623e-01],
       [5.24294388e-01, 4.75705612e-01],
       [9.66445040e-01, 3.35549598e-02],
       [9.58298573e-01, 4.17014269e-02],
       [9.69506719e-01, 3.04932806e-02],
       [4.68949978e-15, 1.00000000e+00],
       [9.58212166e-01, 4.17878340e-02],
       [3.03455783e-01, 6.96544217e-01],
       [6.81868908e-01, 3.18131092e-01]])

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(), X_train, y_train, cv=5)

array([0.752     , 0.776     , 0.768     , 0.81451613, 0.79032258])